config/routes.rb
Renavatio::Application.routes.draw do
  resources :vital_signs

  resources :staffs

  resources :admins

  resources :patients do
    resources :visits
  end

  match '/login' => 'sessions#new'
  match '/auth' => 'sessions#create'
  match '/logout' => 'sessions#destroy'
  match '/specific_patient' => 'patients#specific_patient'

  root :to => 'sessions#new'

end

app/models/vital_sign.rb
class VitalSign < ActiveRecord::Base
  attr_accessible :bp1, :bp2, :height, :pulse, :respiratory_rate, :temperature, :weight, :visit_id

  belongs_to :visit
end

app/controllers/vital_signs_controller.rb
class VitalSignsController < ApplicationController
  # GET /vital_signs
  # GET /vital_signs.json
  def index
    @vital_signs = VitalSign.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vital_signs }
    end
  end

  # GET /vital_signs/1
  # GET /vital_signs/1.json
  def show
    @vital_sign = VitalSign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vital_sign }
    end
  end

  # GET /vital_signs/new
  # GET /vital_signs/new.json
  def new
    @vital_sign = VitalSign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vital_sign }
    end
  end

  # GET /vital_signs/1/edit
  def edit
    @vital_sign = VitalSign.find(params[:id])
  end

  # POST /vital_signs
  # POST /vital_signs.json
  def create
    @vital_sign = VitalSign.new(params[:vital_sign])

    respond_to do |format|
      if @vital_sign.save
        format.html { redirect_to @vital_sign, notice: 'Vital sign was successfully created.' }
        format.json { render json: @vital_sign, status: :created, location: @vital_sign }
      else
        format.html { render action: "new" }
        format.json { render json: @vital_sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vital_signs/1
  # PUT /vital_signs/1.json
  def update
    @vital_sign = VitalSign.find(params[:id])

    respond_to do |format|
      if @vital_sign.update_attributes(params[:vital_sign])
        format.html { redirect_to @vital_sign, notice: 'Vital sign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vital_sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vital_signs/1
  # DELETE /vital_signs/1.json
  def destroy
    @vital_sign = VitalSign.find(params[:id])
    @vital_sign.destroy

    respond_to do |format|
      format.html { redirect_to vital_signs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vital_signs_helper.rb
module VitalSignsHelper
end

app/views/vital_signs/_form.html.erb
<%= form_for(@vital_sign) do |f| %>
  <% if @vital_sign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vital_sign.errors.count, "error") %> prohibited this vital_sign from being saved:</h2>

      <ul>
      <% @vital_sign.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :bp1 %><br />
    <%= f.number_field :bp1 %>
  </div>
  <div class="field">
    <%= f.label :bp2 %><br />
    <%= f.number_field :bp2 %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br />
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :pulse %><br />
    <%= f.number_field :pulse %>
  </div>
  <div class="field">
    <%= f.label :respiratory_rate %><br />
    <%= f.number_field :respiratory_rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vital_signs/edit.html.erb
<h1>Editing vital_sign</h1>

<%= render 'form' %>

<%= link_to 'Show', @vital_sign %> |
<%= link_to 'Back', vital_signs_path %>

app/views/vital_signs/index.html.erb
<h1>Listing vital_signs</h1>

<table>
  <tr>
    <th>Height</th>
    <th>Weight</th>
    <th>Bp1</th>
    <th>Bp2</th>
    <th>Temperature</th>
    <th>Pulse</th>
    <th>Respiratory rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vital_signs.each do |vital_sign| %>
  <tr>
    <td><%= vital_sign.height %></td>
    <td><%= vital_sign.weight %></td>
    <td><%= vital_sign.bp1 %></td>
    <td><%= vital_sign.bp2 %></td>
    <td><%= vital_sign.temperature %></td>
    <td><%= vital_sign.pulse %></td>
    <td><%= vital_sign.respiratory_rate %></td>
    <td><%= link_to 'Show', vital_sign %></td>
    <td><%= link_to 'Edit', edit_vital_sign_path(vital_sign) %></td>
    <td><%= link_to 'Destroy', vital_sign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vital sign', new_vital_sign_path %>

app/views/vital_signs/new.html.erb
<h1>New vital_sign</h1>

<%= render 'form' %>

<%= link_to 'Back', vital_signs_path %>

app/views/vital_signs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Height:</b>
  <%= @vital_sign.height %>
</p>

<p>
  <b>Weight:</b>
  <%= @vital_sign.weight %>
</p>

<p>
  <b>Bp1:</b>
  <%= @vital_sign.bp1 %>
</p>

<p>
  <b>Bp2:</b>
  <%= @vital_sign.bp2 %>
</p>

<p>
  <b>Temperature:</b>
  <%= @vital_sign.temperature %>
</p>

<p>
  <b>Pulse:</b>
  <%= @vital_sign.pulse %>
</p>

<p>
  <b>Respiratory rate:</b>
  <%= @vital_sign.respiratory_rate %>
</p>


<%= link_to 'Edit', edit_vital_sign_path(@vital_sign) %> |
<%= link_to 'Back', vital_signs_path %>