config/routes.rb
Renavatio::Application.routes.draw do
  resources :vital_signs

  resources :staffs

  resources :admins

  resources :patients do
    resources :visits
  end

  match '/login' => 'sessions#new'
  match '/auth' => 'sessions#create'
  match '/logout' => 'sessions#destroy'
  match '/specific_patient' => 'patients#specific_patient'

  root :to => 'sessions#new'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :date_of, :type_of, :chief_complaint, :plan, :assessment, :patient_id, :staff_id, :attestation_date

  has_many :vital_signs

  belongs_to :patient
  belongs_to :staff

  validates :chief_complaint, presence: { message: "Deceased" }
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
    render "shared/template"
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new
    @patient = Patient.find(params[:patient_id])
    @staffs = Staff.all.collect{|emp| ["#{emp.firstname} #{emp.lastname}", emp.id]}
    # staffs.each do |staff|
    #   staffs << ["#{staff.firstname} #{staff.lastname}", staff.id]
    # end
    render "shared/single"
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @staffs = Staff.all.collect{|emp| ["#{emp.firstname} #{emp.lastname}", emp.id]}
    render "shared/single"
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])
    @visit.patient_id = params[:patient_id]
    respond_to do |format|
      if @visit.save
        format.html{ redirect_to patient_visits_path(@visit.patient_id)}
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to patient_visits_path(params[:patient_id]) }
      format.json
    end
  end

  private

  def set_visit_attestation(visit, date)
    # testing how to call controller private variable in rspec
    # visit.attestation_date = date
    # visit.update_attributes(:attestation_date => date)
  end

  def verify_visit_attestation(visit)
    visit.attestation_date?
  end

end

app/helpers/visits_helper.rb
module VisitsHelper

	def create_visit_options(visit, patient_id)
		visit ||= []
		output = ""
		id = visit.get(:id)
		unless visit.blank?
      param_hash = {:patient_id => patient_id, :id => id}
			output += link_to("Edit", edit_patient_visit_path(param_hash), :class => 'btn btn-default').html_safe
			output += link_to("Delete", patient_visit_path(param_hash), :method => :delete, :class => 'btn btn-default delete-visit-btn').html_safe
		end
		output.html_safe
	end

	def generate_new_visit(visit, patient_id)
    visit_id = link_to visit.id, edit_patient_visit_path(:patient_id => patient_id, :id => visit.id)
		CollectionDisplay.new([
      {:name => :id, :value => visit.id, :display_value => visit_id},
      {:name => :type_of, :value => visit.type_of, :display_value => determine_visit_type(visit.type_of)},
      {:name => :chief_complaint, :value => visit.chief_complaint, :display_value => visit.chief_complaint},
      {:name => :updated_at, :value => visit.updated_at, :display_value  => visit.updated_at},
      {:name => :created_at, :value => visit.created_at, :display_value => visit.created_at},
    ])
	end

  def determine_visit_type(type)
    types = ["None", "Consultation", "Progress Note", "Injection Session"]
    types[type]
  end

  def visit_form_output(visit, patient, staff)
    unless visit.blank? || patient.blank? || staff.blank?
      CollectionDisplay.new([
        {:name => :visit_type, :value => visit.type_of, :display_value => visit_type_select(visit.type_of)},
        {:name => :staff, :value => visit.staff_id, :display_value => staff_select(@staffs, visit.staff_id)}
      ])
    end
  end

  def visit_type_select(selected = "")
    select_tag(
      "typelist",
      options_for_select(
        [["Consultation", 1],
        ["Progress Note", 2],
        ["Injection Session", 3]],
        :selected => selected
      ), :class => "form-control",
      :place_holder => "Please select an option",
      :name => "visit[type_of]"
    ).html_safe
  end

  def staff_select(staffs, selected = "")
    select_tag("staffs",
      options_for_select(staffs, :selected => selected),
      :class => "form-control",
      :name => "visit[staff_id]"
    )
  end

end

app/views/visits/_edit.html.erb
<%= render :partial => "shared/form", :locals => {
  :item => visit_form_output(@visit, @patient, @staffs),
  :rows => %w(VisitType Staff),
  :path => edit_patient_visit_path(@patient.id),
  :title => "<h4>Edit Visit</h4>".html_safe,
  :method => "PUT"
} %>

app/views/visits/_index.html.erb
<%= render :partial => "shared/collections",
  :locals => {
    :collection => create_collections(@visits, "generate_new_visit", params[:patient_id]),
    :columns => ["TypeOf", "ChiefComplaint", "CreatedAt"],
    :options => "create_visit_options",
    :options_extra => params[:patient_id]
  }
%>


<%= render :partial => "shared/javascript_controller_action" %>

app/views/visits/_new.html.erb
<h1>New visit</h1>

<%= form_tag patient_visits_path, :method => :post, :role => "role", :class => "form-horizontal" do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <label class="form-label col-lg-offset-2 col-sm-10 col-md-10 col-lg-2" for="typelist">Visit Type</label>
    <div class="col-sm-10 col-md-10 col-lg-4">
      <%= select_tag("typelist", options_for_select([["Consultation", 1],["Progress Note", 2], ["Injection Session", 3]]), :class => "form-control", :place_holder => "Please select an option", :name => "visit[type_of]").html_safe %>
    </div>
  </div>
  <div class="form-group">
    <label class="form-label col-lg-offset-2 col-sm-10 col-md-10 col-lg-2" for="staffs">Staff</label>
    <div class="col-sm-10 col-md-10 col-lg-4">
      <%= select_tag("staffs", options_for_select(@staffs), :class => "form-control", :name => "visit[staff_id]") %>
    </div>
  </div>

  <div class="form-group">
    <label class="form-label col-lg-offset-2 col-sm-10 col-md-10 col-lg-2" for="staffs">Patient Info</label>
    <div class="col-sm-10 col-md-10 col-lg-4">
      <label class="form-control"><%= "#{@patient.firstname} #{@patient.lastname}" %></label>
    </div>
  </div>

  <div class="form-group">
    <label class="form-label col-lg-offset-2 col-sm-10 col-md-10 col-lg-2" for="chief_complaint">Chief Complaint</label>
    <div class="col-sm-10 col-md-10 col-lg-4">
      <input type="text" class="form-control" name="visit[chief_complaint]" />
    </div>
  </div>

  <div class="form-group">
    <label class="form-label col-lg-offset-2 col-sm-10 col-md-10 col-lg-2" for="plan">Plan</label>
    <div class="col-sm-10 col-md-10 col-lg-4">
      <input type="text" class="form-control" name="visit[plan]" />
    </div>
  </div>

  <div class="form-group">
    <label class="form-label col-lg-offset-2 col-sm-10 col-md-10 col-lg-2" for="assessment">Assessment</label>
    <div class="col-sm-10 col-md-10 col-lg-4">
      <input type="text" class="form-control" name="visit[assessment]" />
    </div>
  </div>

  <div class="form-group">
    <label class="form-label col-lg-offset-2 col-sm-10 col-md-10 col-lg-2" for="plan">Attestation Date</label>
    <div class="col-sm-10 col-md-10 col-lg-4">
      <input type="text" class="form-control" id="attest-date" name="visit[attestation_date]" />
    </div>
  </div>

  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Create</button>
    <%= link_to 'Back', patient_visits_path, :class => "btn" %>
  </div>

<% end %>

app/views/visits/_sidebar_edit.html.erb
<div class="sidebar">
	<div class="list-group">
		<%= link_to "View All Patients", patients_path, :class => "list-group-item" %>
		<%= link_to "New Patient", new_patient_path, :class => "list-group-item" %>
	</div>
	<% if @staff %>
		<div class="list-group">
			<%= link_to "View Entire Staff", staffs_path, :class => "list-group-item" %>
			<%= link_to "New Staff", new_staff_path, :class => "list-group-item" %>
		</div>
	<% end %>
</div>

app/views/visits/_sidebar_index.html.erb
<div class="sidebar">
	<div class="list-group">
		<%= link_to "View All Patients", patients_path, :class => "list-group-item" %>
		<%= link_to "New Patient", new_patient_path, :class => "list-group-item" %>
	</div>
	<% if @staff %>
		<div class="list-group">
			<%= link_to "View Entire Staff", staffs_path, :class => "list-group-item" %>
			<%= link_to "New Staff", new_staff_path, :class => "list-group-item" %>
		</div>
	<% end %>
</div>

app/views/visits/_sidebar_new.html.erb
<div class="sidebar">
	<div class="list-group">
		<%= link_to "View All Patients", patients_path, :class => "list-group-item" %>
		<%= link_to "New Patient", new_patient_path, :class => "list-group-item" %>
	</div>
	<% if @staff %>
		<div class="list-group">
			<%= link_to "View Entire Staff", staffs_path, :class => "list-group-item" %>
			<%= link_to "New Staff", new_staff_path, :class => "list-group-item" %>
		</div>
	<% end %>
</div>