config/routes.rb
Renavatio::Application.routes.draw do
  resources :vital_signs

  resources :staffs

  resources :admins

  resources :patients do
    resources :visits
  end

  match '/login' => 'sessions#new'
  match '/auth' => 'sessions#create'
  match '/logout' => 'sessions#destroy'
  match '/specific_patient' => 'patients#specific_patient'

  root :to => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Renavatio">
<head>
  <title>Renavatio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div>
		<div class="account_section">
			<% if logged_in? -%>
				<div id="profile-nav" class="pull-right">Welcome <%= session[:name] %> <%= link_to "Logout", logout_path %></div>
			<% end %>
		</div>
		<% if logged_in? -%>
			<div class="navigation">
				<div class="navbar navbar-default" role="navigation">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="#">Dashboard</a>
	        </div>
	        <div class="navbar-collapse collapse">
	          <ul class="nav navbar-nav">
	            <li><%= link_to "Staff", staffs_path %></li>
	            <li class="dropdown">
	              <a href="/patients" class="dropdown-toggle" data-toggle="dropdown">Patients <b class="caret"></b></a>
	              <ul class="dropdown-menu">
	                <li><%= link_to "View Patients", patients_path %></li>
	                <li><a href="#">Another action</a></li>
	                <li><a href="#">Something else here</a></li>
	                <li class="divider"></li>
	                <li class="dropdown-header">Nav header</li>
	                <li><a href="#">Separated link</a></li>
	                <li><a href="#">One more separated link</a></li>
	              </ul>
	            </li>
	          </ul>
	        </div><!--/.nav-collapse -->
	      </div>
			</div>
		<% end %>
		<div class="body">
			<%= yield %>
		</div>
	</div>
</body>
</html>